In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]



In [5]:
print(data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [9]:
boston_df = pd.DataFrame(data, columns=["CRIM",   
"ZN",     
"INDUS",  
"CHAS",   
"NOX",    
"RM",     
"AGE",    
"DIS",    
"RAD",    
"TAX",
"PTRATIO",
"B",      
"LSTAT"])

In [11]:
boston_df['MEDV'] = target

In [16]:
boston_df.to_csv("boston_dataset.csv",index=False)

In [17]:
pd.read_csv("boston_dataset.csv")

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [ ]:
import pandas as pd
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
boston_df.head(3)

In [ ]:
boston_df['VAL'] = boston.target

In [ ]:
boston_df.describe()

In [ ]:
from sklearn.model_selection import train_test_split
X = boston_df[boston_df.columns[:13]]
Y = boston_df['VAL']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.33, random_state = 5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)



In [ ]:
from sklearn.linear_model import LinearRegression

# Instancio mi regresion
boston_houseprice_lm = LinearRegression()

In [ ]:
# Entreno con mi conjunto de entrenamiento (imaginemos que todo el dataset)
boston_houseprice_lm.fit(X_train, Y_train)

In [ ]:
boston_houseprice_lm.coef_

In [ ]:
 pd.DataFrame({'columns': X.columns, 'coefs': boston_houseprice_lm.coef_})

In [ ]:
boston_houseprice_lm.intercept_

In [ ]:
import matplotlib.pyplot as plt
Y_pred = boston_houseprice_lm.predict(X_test)

plt.scatter(Y_test, Y_pred)
plt.xlabel("Prices: $Y_i$")
plt.ylabel("Predicted prices: $\hat{Y}_i$")
plt.title("Prices vs Predicted prices: $Y_i$ vs $\hat{Y}_i$")
plt.show()

In [ ]:
result = pd.DataFrame()
result["VAL"] = Y_test
result["VALPRED"] = Y_pred
result["ERRORVAL"] = abs(result.VAL - result.VALPRED)
result.head(3)

In [ ]:
import matplotlib.pyplot as plt


result.plot(kind='scatter', x='VAL', y='ERRORVAL')
plt.show()

In [ ]:
from sklearn.metrics import r2_score

print(r2_score(Y_test, Y_pred))


In [ ]:
Y_pred = boston_houseprice_m.predict(X_test)
r2_score(Y_test, Y_pred) 

In [ ]:
from sklearn.metrics import mean_squared_error
print('Linear model, coefficients: ', boston_houseprice_lm.coef_)
print("Mean squared error (linear model): {:.2f}".format(mean_squared_error(Y_test, Y_pred)))
print("r2_score (linear model): {:.2f}".format(r2_score(Y_test, Y_pred)))


In [ ]:
from pandas.plotting import scatter_matrix
scatter_matrix(boston_df, alpha=0.2, figsize=(6, 6), diagonal='kde')

In [ ]:
from sklearn.linear_model import Ridge 

# Instancio mi regresion
rigde_model = Ridge()
rigde_model.fit(X_train, Y_train)
rigde_model.coef_


In [ ]:
Y_pred = rigde_model.predict(X_test)
r2_score(Y_test, Y_pred) 

In [ ]:
from sklearn.linear_model import Lasso 

# Instancio mi regresion
lasso_model = Lasso()
lasso_model.fit(X_train, Y_train)
lasso_model.coef_

In [ ]:
Y_pred = lasso_model.predict(X_test)
r2_score(Y_test, Y_pred) 

In [ ]:
from sklearn.linear_model import LassoCV

# Instancio mi regresion
model = LassoCV()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
r2_score(Y_test, Y_pred) 

In [ ]:
from sklearn.linear_model import RidgeCV

# Instancio mi regresion
model = RidgeCV()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
r2_score(Y_test, Y_pred)